"""
Django settings for senpick project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

ALLOWED_HOSTS = ['senpick.kr', 'web', '127.0.0.1', 'localhost', os.getenv('ALLOWED_HOSTS')]

# SECURE_SSL_REDIRECT = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 소셜로그인 추가
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.naver',
    # 'allauth.socialaccount.providers.kakao', # 제외
    'app', # 앱 이름 추가
]

# 소셜 로그인 내용
SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_EMAIL_VERIFICATION = 'none'

SOCIALACCOUNT_ADAPTER = 'app.adapter.MySocialAccountAdapter'
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_CONFIRM_LOGIN_ON_GET = False
AUTH_USER_MODEL = 'app.User'

LOGIN_REDIRECT_URL = '/social/redirect/'
ACCOUNT_LOGOUT_REDIRECT_URL = '/'

CSRF_TRUSTED_ORIGINS = [
    "https://senpick.kr",
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware', # 소셜로그인 기능
]

ROOT_URLCONF = 'senpick.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], # 템플릿 경로 설정
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'senpick.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'senpick_db',  # 데이터베이스 이름
        'USER': os.getenv('MYSQL_USER'),        # MySQL 사용자
        'PASSWORD': os.getenv('MYSQL_PASSWORD'), # MySQL 비밀번호
        'HOST': os.getenv('MYSQL_HOST'),   # 로컬 호스트
        'PORT': '3306',        # MySQL 포트
    }
} 

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# STATIC_URL = 'static/'
STATIC_URL = '/static/'
if os.getenv("ENVIRONMENT") == 'PRODUCTION': # 배포용 환경 변수 설정
    STATIC_ROOT = os.path.join(BASE_DIR, 'static') # 배포용 세팅
else:
    STATICFILES_DIRS = [BASE_DIR / "static"] # 로컬 세팅

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# 이메일 인증 관련
# 1. 이메일 백엔드 설정
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # 테스트 용
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# 2. SMTP 서버 호스트 (예: Gmail SMTP, Naver SMTP 등)
# EMAIL_HOST = 'email-smtp.ap-northeast-2.amazonaws.com'       
EMAIL_HOST = 'smtp.gmail.com' # Gmail을 쓰는 경우
# EMAIL_HOST = 'smtp.naver.com'     # 네이버 SMTP를 쓰는 경우

# 3. SMTP 서버 포트
#    └– 대부분 TLS(STARTTLS) 사용 시 587, SSL(SSL/TLS)을 직접 사용할 때는 465
EMAIL_PORT = 587

# 4. TLS/SSL 설정
EMAIL_USE_TLS = True   # STARTTLS(업그레이드 보안)를 쓰는 경우
# EMAIL_USE_SSL = False   # SSL 연결을 바로 여는 경우 (이 둘을 동시에 True로 두지는 않습니다)

# 5. SMTP 서버 로그인 계정(아이디)
#    └– 실제 메일을 발송할 계정(이메일주소)을 적어야 합니다.
EMAIL_HOST_USER = os.getenv('YOUR_EMAIL')

# 6. SMTP 서버 로그인 비밀번호
#    └– 위 계정의 비밀번호 또는 “앱 비밀번호”(2차 인증을 켠 경우) 등을 입력
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_PASSWORD')

# 7. 기본 발신자 주소
#    └– send_mail() 호출 시, “From” 에 기본으로 들어갈 이메일/문자열
DEFAULT_FROM_EMAIL = 'Senpick <no-reply@senpick.com>'



MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
AWS_REGION = "ap-northeast-2"

AWS_STORAGE_BUCKET_NAME = "senpickbucket"
AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com"  # 또는 CloudFront 도메인

# 미디어 경로 커스텀 시 사용
MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/media/"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# CSRF 쿠키도 https에만 전송
CSRF_COOKIE_SECURE = True

# 세션 쿠키도 https에만 전송
SESSION_COOKIE_SECURE = True

# 보안 헤더 (옵션)
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True

# X-Forwarded-Proto 헤더 사용 허용 (리버스 프록시 환경일 경우)
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

