# Generated by Django 5.2 on 2025-06-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('nickname', models.CharField(max_length=30)),
                ('birth', models.CharField(max_length=8)),
                ('gender', models.CharField(max_length=8)),
                ('job', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_image', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(default='guest', max_length=10)),
                ('social_provider', models.CharField(blank=True, max_length=10, null=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
