# Generated by Django 5.2 on 2025-06-10 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_user_deleted_at_user_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatrecommend",
            name="msg_id",
            field=models.ForeignKey(
                db_column="MSG_ID",
                on_delete=django.db.models.deletion.CASCADE,
                to="app.chatmessage",
            ),
            preserve_default=False,
        ),
    ]
