# Generated by Django 5.2 on 2025-06-11 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_chatrecommend_msg_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="user_id",
            field=models.ForeignKey(
                db_column="USER_ID",
                on_delete=django.db.models.deletion.CASCADE,
                to="app.user",
            ),
        ),
    ]
