# Generated by Django 5.2 on 2025-06-11 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_chat_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatrecommend",
            name="reason",
            field=models.CharField(
                blank=True, db_column="REASON", max_length=255, null=True
            ),
        ),
    ]
